backend:
  name: github
  base_url: https://api.staticweb-01.etalab.gouv.fr
  site_domain: eig2.etalab.gouv.fr
  repo: Skeith918/blog2-eig2

media_folder: "img/portfolio"

collections:
  - name: "posts"
    label: "challenges"
    folder: "_posts"
    sort: "date:desc"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout",  widget: "hidden", default: "default"}
      - {label: "Titre", name: "modal-id", widget: "string", tagname: "h1"}
      - {label: "Date", name: "project-date", widget: "datetime", format: "MM-YYYY"}
      - {label: "Image", name: "img", widget: "image"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Categorie", name: "category", widget: "string"}

  - name: "section"
    label: "Section"
    folder: "_includes"
    create: true
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Contenu", name: "body", widget: "markdown"}

