backend:
  name: github
  base_url: https://api.staticweb-01.etalab.gouv.fr
  site_domain: eig2.etalab.gouv.fr
  repo: Skeith918/blog2-eig2

media_folder: "img/uploads"

collections:
  - name: "post"
    label: "Articles"
    folder: "_posts"
    sort: "date:desc"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", default: "post"}
      - {label: "Titre", name: "title", widget: "string", tagname: "h1"}
      - {label: "Contenu", name: "body", widget: "markdown"}
      - {label: "Categorie", name: "categories", widget: "string"}
    meta:
      - {label: "Publish Date", name: "date", widget: "datetime", format: "DD-MM-YYYY hh:mm:ss"}

  - name: "section"
    label: "Section"
    folder: "_includes"
    create: true
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Contenu", name: "body", widget: "markdown"}

